### ISSUE TITLE
Use git hooks?

### ISSUE THREAD

**Issue by shyim** [FriendsOfShopware/default-plugin-repo#2]
Register a git hook for checking code styling before creating a commit.

**Comment by JoshuaBehrens** [comment]
I do not want to be forced to have a certain tool installed before commiting anything.

If I edit php-files and need php-cs-fixer installed I do agree to a certain degree. The projects should ship every tool required in git hooks via composer dev requirements to ensure the same behaviour on any machine.

**Comment by eemzet** [comment]
I like the idea and i think it's a big step towards good code quality if we use checks for code style. With the git hooks we can force the others to use this checks and ensure that these checks were passed.

**Comment by Crease29** [comment]
I also like the idea to check code styles. But why don't we just use it in our Travis process? That wouldn't require to have certain tools installed in our dev environment and a PR can't be merged if there are issues.

**Comment by xf-** [comment]
Most projects use something like https://scrutinizer-ci.com or travis
